# Generated by Django 5.0.6 on 2024-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='beds',
            field=models.CharField(choices=[('DOUBLE', 'Double'), ('QUEEN', 'Queen'), ('KING', 'King')], max_length=10),
        ),
    ]
