# Generated by Django 5.0.6 on 2024-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(choices=[('D', 'Doubble'), ('Q', 'Queen'), ('K', 'King')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('STA', 'Standard'), ('DEL', 'Deluxe'), ('SUI', 'Suite')], max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description of the room', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
    ]
