# Generated by Django 5.0.6 on 2024-06-30 16:44

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomcategory_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='avaliable',
            field=models.BooleanField(default=True, help_text='Check if the room is avaliable'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='image_alt',
            field=models.CharField(default='placeholder default room image', help_text='Enter a breif description of the image', max_length=100),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the room', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='room-categories/'),
        ),
    ]
