# Generated by Django 5.0.6 on 2024-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_name_alter_room_beds_alter_room_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.CharField(choices=[('D', 'Doubble'), ('Q', 'Queen'), ('K', 'King')]),
        ),
    ]
