# Generated by Django 5.0.6 on 2024-07-09 13:29

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_status_room_avaliable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, max_length=1000, quality=75, scale=None, size=[400, 400], upload_to='room-categories/'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='image_alt',
            field=models.CharField(default='Default room image', help_text='Enter a breif description of the image', max_length=100),
        ),
    ]
