# Generated by Django 5.0.6 on 2024-06-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_Id',
            new_name='booking_id',
        ),
    ]
